# Generated by Django 2.2.28 on 2025-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20250131_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
