# Generated by Django 2.2.28 on 2025-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20250214_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
