# Generated by Django 2.2.28 on 2025-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_auto_20250219_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'verbose_name_plural': 'Forum categories'},
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
