# Generated by Django 2.2.28 on 2025-02-19 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0013_auto_20250219_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='voted_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
